### ISSUE TITLE
prepare_working_table Performance Investigation

### ISSUE THREAD

**Issue by dsteinich** [ACWI-SSWD/nldi-db#11]
The plpgsql function prepare_working_table copies all potential data for navigation within a region into a temporary table for further filtering. Investigate if more (or all) pre-filtering can be done to limit the number of rows processed with each navigation request.

**Comment by dblodgett-usgs** [comment]
Put additional performance enhancements into new issues for the WQP Site Context milestone.

**Comment by jkreft-usgs** [comment]
Resolved, prepare_working_table is no longer used
