### ISSUE TITLE
Allow specification of any registered point as the starting point for navigation.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-db#15]
The watershed starting point specifier should be able to be any of the registered starting points. Given a valid starting point, the service would find the associated reachcode/comid/measure, use sensible defaults as necessary, and do all the other functions as usual.

**Comment by dblodgett-usgs** [comment]
Added to the WDP Discovery Milestone, but not strictly needed if it's more than a trivial amount of work.

**Comment by jkreft-usgs** [comment]
Done, for example, http://cida.usgs.gov/nldi/wqp/21NEB001_WQX-LBB1CUBCRK04/navigate/UT/wqp?distance=16.1
