### ISSUE TITLE
Develop basic strategy to build cache of navigation results.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-db#18]
For now, lets cache all the comids in the WBDPP table. The idea is that a cache builder would look at all the comids in that table and run what's needed to generate the cached content.

In other words: As an NLDI administrator, I want to be able to cache navigation results for everything in one of the indexed layers.

**Comment by dblodgett-usgs** [comment]
May not be needed based on outcome of #11 and #19

**Comment by jkreft-usgs** [comment]
not needed
