### ISSUE TITLE
(How) should we handle the difference between dataset and NLDI NHDPlus versions?

### ISSUE THREAD

**Issue by coobr01** [ACWI-SSWD/nldi-db#23]
NLDI will need a way to handle the situation where a dataset is provided to the crawler which contains reachcode and measure information from a vintage of NHDPlus that does NOT match the vintage loaded in NLDI.

**Comment by dblodgett-usgs** [comment]
My feeling on this is that we shouldn't worry about it in the context of the NLDI. At some stage a stand alone service, which may be a resource for the NLDI, should be created that can migrate reachcode/measures from one dataset to another, but that shouldn't be the job of the NLDI its self.

That said, I would see some value in having the NHDPlus V1 - V2 cross walk in the system to support atleast those two datasets. Are there other major versions that would make some sense to support?

**Comment by dblodgett-usgs** [comment]
Closing in favor of future illustrations of this issue.
