### ISSUE TITLE
Add lakes to the database.

### ISSUE THREAD

**Issue by lawinslow** [ACWI-SSWD/nldi-db#29]
Are lakes included in the linked database? 

Adding some additional questions for this issue -- dblodgett-usgs
- Should they be included as 'special' features that crawlers would know about for indexing purposes? 
- What is the best way to link them to the network of conveyances?
- Do 'double line streams' count as lakes?
- How would we curate 'the official' set of linkable lake features?

**Comment by dblodgett-usgs** [comment]
No, not currently. The system only includes flowlines and things that can be cast as points. 

There is some notion that things, like lakes, that can be attached to a catchment through a catchment indexing process, http://acwi.gov/monitoring/conference/2014/2ConcurrentSessions/M6/M6Reid.pdf, could be incorporated into the system fairly easily. 

IMHO, the current situation with waterbodies in NHD (they are largely cartographic features) makes it a difficult task to incorporate them into the 'network' without going to some sort of catchment indexing process. 

This issue would get us part of the way there: https://github.com/ACWI-SSWD/nldi-crawler/issues/10 I expect a number of lakes data sources could be ingested through this kind of process or have already been indexed and could just be loaded.

**Comment by lawinslow** [comment]
> IMHO, the current situation with waterbodies in NHD (they are largely cartographic features) makes it a difficult task to incorporate them into the 'network' without going to some sort of catchment indexing process.

But they can be directly linked to the flowline that traverses the lake feature, no?

**Comment by dblodgett-usgs** [comment]
Yes, but there is a lot of complication with doing that. The NHD team has gone back and forth and is generally rethinking how to deal with waterbodies. Happy too discuss more offline.

**Comment by dblodgett-usgs** [comment]
Will take this up under https://github.com/ACWI-SSWD/nldi-crawler/issues/10 and other work to index polygon features.
