### ISSUE TITLE
Remove or rename errored tables under nldi_data schema

### ISSUE THREAD

**Issue by coobr01** [ACWI-SSWD/nldi-db#36]
Seems to be in both database instances. 

![image](https://cloud.githubusercontent.com/assets/1842830/21506299/2139f220-cc3d-11e6-92a3-fb2957e5dffe.png)

Looks like it came from https://github.com/ACWI-SSWD/nldi-db/blob/master/nldi-liquibase/src/main/resources/liquibase/nldi_data/tables.sql

**Comment by dblodgett-usgs** [comment]
@EthanGrahn -- is this still an issue?

**Comment by EthanGrahn** [comment]
@dblodgett-usgs If this is referring to tables with `_temp`, then yes. They are supposed to be automatically created by the crawler and cleaned up after ingestion is complete. The `feature; select * from pg_class;` is intended to prevent a specific SQL injection, so that's intended.

**Comment by dblodgett-usgs** [comment]
OK -- We'll leave this open. It would make sense to have those temp tables get dropped if not needed anymore.
